project_id = "biknetlbajwbrxqaafsp"

[functions.chat]
verify_jwt = false

[functions.orchestrator]
verify_jwt = false

[functions.send-admin-alert]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false